name: Update dagster-reserach

on:
 push:
    branches:
      - 'master'


jobs:
  update_framework:
    runs-on: ubuntu-latest
    steps:
      - name: server
        uses: appleboy/ssh-action@master
        with:
          host: 13.231.118.166
          username: ubuntu
          key: ${{ secrets.DEVOPS_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/devops/
            sudo ansible-playbook udpate_dagster.yml
